export const STATE_TOP_POSTS = "STATE_TOP_POSTS";
export const STATE_SELECTED_POST = "STATE_SELECTED_POST";

export const MUT_SET_TOP_POSTS = "MUT_SET_TOP_POSTS";
export const MUT_SET_READ_STATUS = "MUT_SET_READ_STATUS";
export const MUT_SET_SELECTED_POST = "MUT_SET_SELECTED_POST";
export const MUT_DELETE_POST = "MUT_DELETE_POST";
export const MUT_DELETE_ALL = "MUT_DELETE_ALL";
export const MUT_TOGGLE_MENU = "MUT_TOGGLE_MENU";

export const ACT_GET_TOP_POSTS = "ACT_GET_TOP_POSTS";

export const NAMESPACE = "posts";
